### ISSUE TITLE
Deprecated function: unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in CommerceProductEntityController->attachLoad()

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/commerce#7] opened 2024-10-15 21:09 UTC
> Deprecated function: unserialize(): Passing null to parameter #1 ($data) of type string is deprecated in CommerceProductEntityController->attachLoad() (line 150 of /app/httpdocs/modules/commerce/modules/product/includes/commerce_product.controller.inc).

I get this on the edit form of a product. I created a product using the default product type. The simplest approach would be to only use `unserialize()` if `$product->data` is not `null`. 

```
$product->data = $product->data ? unserialize($product->data) : array();
```

I didn't look into where data is coming from. From the cache perhaps?

**Comment by elisseck** [comment] 2024-10-16 20:55
Thank you for reporting!

I wasn't able to reproduce this one yet, can you give me a little more information on your testing env such as backdrop version and PHP version?

This is where I created a default type product, so you can also let me know if i'm doing something different than you were:

![image](https://github.com/user-attachments/assets/e464fd7e-fafd-48b9-89f6-c07fc51926af)

I think your change sounds like a fine one, i'd just like to be able to confirm that it did fix the problem you are experiencing.

**Comment by herbdool** [comment] 2024-10-17 14:31
I did a fresh install so there's nothing else other than the standard core modules and Commerce modules (all of them) enabled. I'm still getting that error. I'm testing locally on Lando with the latest 1.x and PHP 8.2:

```
Backdrop CMS:                    1.30.x-dev
Installation profile:            standard
PHP version:                     8.2.23
Drupal 7 compatibility:          on
Database server:                 10.6.5-MariaDB
Web server:                      Apache/2.4.62 (Debian)
jQuery version:                  3.7.1
jQuery UI version:               1.14.0
CKEditor 5 version: 42.0.2       Used in formats: Basic
```

I think the warning was introduced in PHP 8.1.

`$data` matches the data column in `commerce_product`: "A serialized array of additional data.", which defaults to `NULL`. And there are also data columns for customer, line_item, order, payment.

Here's a similar Drupal Commerce issue (though for Drupal 8+): https://www.drupal.org/project/commerce/issues/3275408

**Comment by herbdool** [comment] 2024-10-17 14:53
There are two approaches: on `CommerceProductEntityController::save()` it could save an empty string to `data` if it's empty:

```
  if (empty($entity->data)) {
      $entity->data = '';
    }
```

Though I'm not sure if that has an advantage over my first approach above.

**Comment by elisseck** [comment] 2024-10-17 14:58
I see it! I just didn't have deprecated notices on for this new install :facepalm: 

I think we will see more of these around since it's a pattern for most of the commerce entities and new PHP is going to start issuing warnings instead of notices: https://www.php.net/manual/en/function.unserialize.php

There is also some good discussion here about it: https://www.drupal.org/project/drupal/issues/3300404 and I kind of like this `safeUnserialize()` direction they're going, but that would be more of a core thing. Maybe we can use that here in the time being though.

**Comment by herbdool** [comment] 2024-10-17 15:07
Or it's something for `entity_plus` since I think it's being handled there.

**Comment by elisseck** [comment] 2024-10-30 20:18
I thought about this a bit more and actually I really don't like that `@unserialize($value);` thing... I think PHP is the culprit and we REALLY should just get an exception instead of a warning but... here we are.

I think for our purposes now, i'm going to implement your original solution and just ignore the world where we somehow get a non-null value that isn't serialized data. If we see a warning for that reason later, we can return to this.

Edit: It somehow snuck into 9d82605e so i'm going to close this for now. We can circle back if it comes up again!

**Closed as completed** 2024-10-30 20:32 UTC
